/**
 * dataModel.js — Single Source of Truth
 *
 * Every row: { id, raw, user, computed }
 * - raw: immutable parsed import data
 * - user: user overrides and settings
 * - computed: derived output (what UI/export reads)
 *
 * Rule: table, sidebar, and export ALL read from `computed`.
 * Call recompute() whenever raw, user, or globals change.
 */

window.PSB = window.PSB || {};

// ── Row ID counter ────────────────────────────────────────
var _nextId = 1;

// ── Frequency → Letter mapping (fixed, never dynamic) ────
var FREQ_LETTER_MAP = {
  '1 in 1': 'A',
  '1 in 2': 'B',
  '1 in 3': 'C',
  '1 in 4': 'D',
  '1 in 5': 'E',
  '1 in 10': 'F',
  '1 in 20': 'G',
  '1 in 50': 'H',
  'First and Last': 'I',
};

/**
 * Generate the Output Tag for a dim tag + frequency.
 *
 * Non-OP2000: <LetterPrefix>REF-<zero-padded dim tag>
 * OP2000: raw dim tag only (no REF-, no letter)
 *
 * @param {string} dimTag — raw dim tag value
 * @param {string} frequency — inspection frequency string
 * @param {boolean} isOp2000
 * @returns {string}
 */
function generateOutputTag(dimTag, frequency, isOp2000) {
  // Zero-pad to 2 digits if numeric
  var padded = /^\d+$/.test(dimTag) ? dimTag.padStart(2, '0') : dimTag;

  if (isOp2000) {
    return padded;
  }

  var letter = FREQ_LETTER_MAP[frequency] || '';
  return letter + 'REF-' + padded;
}

/**
 * Check if an output tag matches an auto-generated pattern.
 * Auto-generated: "REF-07", "AREF-07", "BREF-13", "07" (OP2000 padded)
 * If it matches, frequency changes can safely regenerate it.
 */
function isAutoGeneratedTag(tag) {
  if (!tag) return true;
  return /^[A-I]?REF-\d+$/.test(tag) || /^\d{1,2}$/.test(tag);
}

/**
 * Default global settings
 */
function defaultGlobals() {
  return {
    projectId: null,          // UUID assigned on first save — stable key for PDF IDB cache
    faiWarnThreshold: 0.80,   // FAI warn threshold (fraction of tolerance band)
    cmmImportUnits: 'mm',     // units CMM report values are expressed in (mm | inch)
    cmmPartName: '',          // part name extracted from CMM report header
    importUnits: 'mm',        // 'mm' or 'inch'
    displayUnits: 'inch',     // 'mm', 'inch', or 'both'
    exportUnits: 'inch',
    platingThickness: 0,
    platingUnits: 'inch',
    inchPrecision: 4,
    mmPrecision: 3,
    ops: [50, 60],            // default OPs
    equipmentList: [
      'Calipers',
      'Micrometer',
      'Optical C.',
      'CMM',
      'Height Gage',
      'Gage Block',
      'GO / NO-GO',
      'PASS/FAIL',
      'Drop Indicator',
      'N/A',
    ],
    pdfFileName: null,
    pdfRevision: null,            // string e.g. "Rev B", set when PDF is linked/updated
    pdfRevisionsHistory: [],      // [{ rev, linkedAt }] for record keeping
    balloonRadius: 6,             // balloon circle radius in PDF points — global size for all balloons
    ocrMode: 'pdfjs',             // balloon OCR engine: 'pdfjs' (PDF.js text layer, Claude fallback) | 'claude' (always Claude vision)
    titleBlockTolUnits: 'inch',   // unit system the title block tolerance values are entered in
    titleBlockTol1d: '',          // default tolerance for .X dimensions  (1 decimal place)
    titleBlockTol2d: '',          // default tolerance for .XX dimensions (2 decimal places)
    titleBlockTol3d: '',          // default tolerance for .XXX dimensions (3 decimal places)
    titleBlockTol4d: '',          // default tolerance for .XXXX dimensions (4 decimal places)
    titleBlockTolGdt: '',         // GD&T profile tolerance as global default — overrides decimal-based if set
  };
}

/**
 * Default user overrides for a single row
 */
function defaultUserState() {
  return {
    includeOps: {},          // { [opNumber]: true/false }
    ipc: false,
    isNote: false,
    autoNominal: true,
    platingMode: 'none',     // 'none', '+1xI', '+2xI', '-1xE', '-2xE'
    inspectionFrequency: '',
    inspectionEquipment: '',
    pinGageEnabled: false,
    status: 'none',          // 'none', 'edited', 'complete'
    balloon: null,           // ballooning spatial data (see balloonManager.js); null = no balloon
    gdt: null,               // GD&T structured data (see gdtParser.js); null = not a GD&T row
    overrides: {
      outDrawingSpec: null,  // OP2000 base spec override (drives OUT spec via pipeline)
      outTolPlus: null,      // OP2000 base tol+ override (feeds pipeline)
      outTolMinus: null,     // OP2000 base tol- override (feeds pipeline)
      outputSpec: null,      // Independent OUT spec override (cleared when OP2000 spec changes)
      outputTolPlus: null,   // Independent OUT tol+ override (bypasses pipeline)
      outputTolMinus: null,  // Independent OUT tol- override (bypasses pipeline)
      tolMode: 'sym',        // 'sym' | 'asym' | 'minmax' — per-row UI input mode (math unchanged)
      pinGageValue: null,
      specUnit1: null,
      specUnit2: null,
      specUnit3: null,
      outNominal: null,
      inputTolerance: null,
      outputTag: null,       // null = auto-generate, string = manual override
      // Deprecated (v1 compat — migrated on load, never written)
      outTolerance: null,
      outputTolerance: null,
    },
  };
}

/**
 * Effective dimTag: balloon-created rows treat user.balloon.dimTag as live source
 * of truth; CSV-imported rows fall back to raw.dimTag.
 */
function effectiveDimTag(row) {
  if (row && row.user && row.user.balloon && row.user.balloon.dimTag != null) {
    return String(row.user.balloon.dimTag);
  }
  return (row && row.raw && row.raw.dimTag) || '';
}

/**
 * Create a new row from balloon OCR data.
 * Unlike createRow(): raw is NOT frozen. user.balloon.dimTag is the live dimTag.
 */
function createBalloonRow(dimTag, parsedData, balloonData) {
  parsedData = parsedData || {};
  balloonData = balloonData || {};

  var row = {
    id: _nextId++,
    raw: {
      _source: 'balloon',
      dimTag: String(dimTag),
      drawingSpec: parsedData.drawingSpec || '',
      nominal: parsedData.nominal || parsedData.drawingSpec || '',
      tolerance: parsedData.tolerance || '',
      specUnit1: parsedData.specUnit1 || '',
      specUnit2: parsedData.specUnit2 || '',
      specUnit3: parsedData.specUnit3 || '',
      toleranceText: parsedData.tolerance || '',
      nominalText: parsedData.nominal || parsedData.drawingSpec || '',
      refLoc: '',
      charDsg: '',
    },
    user: defaultUserState(),
    computed: {},
  };

  row.user.balloon = {
    dimTag: dimTag,
    page: balloonData.page,
    anchorBox: balloonData.anchorBox,
    balloonOffset: balloonData.balloonOffset,
    leaderConnectionPoint: balloonData.leaderConnectionPoint,
    dragDirection: balloonData.dragDirection || 'ltr',
    source: balloonData.source || 'manual',
    ocrConfidence: balloonData.ocrConfidence || null,
    ocrEngine: balloonData.ocrEngine || null,
    misalignedRev: null,
    tolType: null,  // 'default' | 'override' | 'profile' — set by popover on confirm
  };

  var featureType = PSB.detectFeatureType(parsedData.drawingSpec || '');
  if (featureType === 'note' || featureType === 'gdt' || featureType === 'thread') {
    row.user.isNote = true;
  }
  if (parsedData.isGDT) row.user.isNote = true;

  return row;
}

/**
 * Create a new row from raw CSV data
 * @param {Object} rawData — parsed CSV fields
 * @returns {Object} row — { id, raw, user, computed }
 */
function createRow(rawData) {
  var row = {
    id: _nextId++,
    raw: Object.freeze(Object.assign({}, rawData)),
    user: defaultUserState(),
    computed: {},
  };

  // Auto-detect notes from drawingSpec
  var featureType = PSB.detectFeatureType(rawData.drawingSpec || '');
  if (featureType === 'note' || featureType === 'gdt' || featureType === 'thread') {
    row.user.isNote = true;
  }

  // Also detect GD&T from specUnit2 (e.g., Concentricity, Position, Flatness)
  if (!row.user.isNote && rawData.specUnit2) {
    var su2 = rawData.specUnit2.trim().toLowerCase();
    var gdtSu2 = ['concentricity', 'position', 'flatness', 'perpendicular',
      'parallel', 'surf profile', 'angular', 'total runout', 'runout'];
    for (var i = 0; i < gdtSu2.length; i++) {
      if (su2.indexOf(gdtSu2[i]) >= 0) {
        row.user.isNote = true;
        break;
      }
    }
  }

  return row;
}

/**
 * Recompute a row's `computed` object from raw + user + globals.
 * This is the ONLY place calculations happen.
 *
 * @param {Object} row — the row to recompute
 * @param {Object} globals — global settings
 * @returns {Object} row — same row, mutated with new computed values
 */
function recompute(row, globals) {
  var raw = row.raw;
  var user = row.user;

  // Balloon-created rows: user.balloon.dimTag is the live source of truth.
  var effDimTag = effectiveDimTag(row);

  // ── Step 0: If note, skip all math ─────────────────────
  if (user.isNote) {
    var ov = user.overrides || {};
    var noteOutputTag = (ov.outputTag !== null && !isAutoGeneratedTag(ov.outputTag))
      ? ov.outputTag
      : generateOutputTag(effDimTag, user.inspectionFrequency || '', false);
    row.computed = {
      isNote: true,
      dimTag: effDimTag,
      outputTag: noteOutputTag,
      drawingSpec: raw.drawingSpec || '',
      outDrawingSpec: ov.outDrawingSpec !== null ? ov.outDrawingSpec : (raw.drawingSpec || ''),
      inputSpec: raw.drawingSpec || '',
      specUnit1: ov.specUnit1 !== null ? ov.specUnit1 : (raw.specUnit1 || ''),
      specUnit2: ov.specUnit2 !== null ? ov.specUnit2 : (raw.specUnit2 || ''),
      specUnit3: ov.specUnit3 !== null ? ov.specUnit3 : (raw.specUnit3 || ''),
      // OP2000 fields (consistent shape with non-note rows — preserve raw values)
      op2000DrawingSpec: ov.outDrawingSpec !== null ? ov.outDrawingSpec : (raw.drawingSpec || ''),
      op2000Nominal: 0,
      op2000Tolerance: raw.tolerance || '',
      op2000DualSpec: ov.outDrawingSpec !== null ? ov.outDrawingSpec : (raw.drawingSpec || ''),
      op2000DualTol: raw.tolerance || '',
      outNominal: ov.outNominal !== null ? ov.outNominal : (raw.nominal || ''),
      outTolerance: raw.tolerance || '',
      inputTolerance: ov.inputTolerance !== null ? ov.inputTolerance : (raw.tolerance || ''),
      pinGage: ov.pinGageValue !== null ? ov.pinGageValue : '',
      platingAnnotation: '',
      platingMode: 'none',
      status: user.status,
      ipc: user.ipc,
      inspectionEquipment: user.inspectionEquipment,
      inspectionFrequency: user.inspectionFrequency,
      includeOps: Object.assign({}, user.includeOps),
      op2kTolPlus: 0,
      op2kTolMinus: 0,
      outTolPlus: 0,
      outTolMinus: 0,
      original: { nominal: 0, tolPlus: 0, tolMinus: 0 },
      output: { nominal: 0, tolPlus: 0, tolMinus: 0 },
    };
    return row;
  }

  // ══════════════════════════════════════════════════════════
  // Type 1 — Parsing: clean up raw data into correct columns
  // ══════════════════════════════════════════════════════════
  var specUnits = PSB.parseSpecUnits(raw.drawingSpec || '');
  var tolParsed = PSB.parseTolerance(raw.toleranceText || raw.tolerance || '');

  var nominal = parseFloat(raw.nominalText || raw.nominal || raw.drawingSpec) || 0;
  var tolPlus = tolParsed.tolPlus;
  var tolMinus = tolParsed.tolMinus;

  // If tolerance was a single ± value from CSV
  if (tolPlus === 0 && tolMinus === 0 && raw.tolerance) {
    var t = parseFloat(raw.tolerance);
    if (!isNaN(t)) {
      tolPlus = t;
      tolMinus = t;
    }
  }

  // ── Unit and precision settings (needed by Type 2 and all downstream) ──
  var importUnits = globals.importUnits || 'mm';
  var secondaryUnits = importUnits === 'mm' ? 'inch' : 'mm';
  var primaryPrec = importUnits === 'inch' ? globals.inchPrecision : globals.mmPrecision;
  var secondaryPrec = secondaryUnits === 'inch' ? globals.inchPrecision : globals.mmPrecision;

  // ══════════════════════════════════════════════════════════
  // Type 2 — Manual Overrides: apply user corrections
  // OP2000 overrides feed into the numeric pipeline so OUT
  // values are derived correctly from the corrected base.
  // ══════════════════════════════════════════════════════════
  var op2000SpecUnit1 = user.overrides.specUnit1 !== null ? user.overrides.specUnit1 : (raw.specUnit1 || specUnits.su1 || '');
  var op2000SpecUnit2 = user.overrides.specUnit2 !== null ? user.overrides.specUnit2 : (raw.specUnit2 || specUnits.su2 || '');
  var op2000SpecUnit3 = user.overrides.specUnit3 !== null ? user.overrides.specUnit3 : (raw.specUnit3 || specUnits.su3 || '');
  var op2000DrawingSpec = user.overrides.outDrawingSpec !== null ? user.overrides.outDrawingSpec : (raw.drawingSpec || '');

  // Angle detection: no unit conversion applied to angle dimensions.
  // Secondary display shows [Angle] instead of a converted value.
  var ANGLE_RE = /angle|°/i;
  var isAngle = ANGLE_RE.test(op2000SpecUnit1) || ANGLE_RE.test(op2000SpecUnit2) ||
                ANGLE_RE.test(op2000SpecUnit3) || ANGLE_RE.test(op2000DrawingSpec);
  // Build OP2000 tolerance display from plus/minus overrides or raw
  var hasOp2kTolOverride = user.overrides.outTolPlus !== null || user.overrides.outTolMinus !== null;
  var op2000Tolerance;
  if (hasOp2kTolOverride) {
    var ovPlus = parseFloat(user.overrides.outTolPlus);
    var ovMinus = parseFloat(user.overrides.outTolMinus);
    if (isNaN(ovPlus) && !isNaN(ovMinus)) ovPlus = ovMinus;
    if (isNaN(ovMinus) && !isNaN(ovPlus)) ovMinus = ovPlus;
    if (!isNaN(ovPlus) && !isNaN(ovMinus)) {
      if (Math.abs(ovPlus - ovMinus) < 1e-10) {
        op2000Tolerance = PSB.formatPrecision(ovPlus, primaryPrec);
      } else {
        op2000Tolerance = '+' + PSB.formatPrecision(ovPlus, primaryPrec) + ' -' + PSB.formatPrecision(ovMinus, primaryPrec);
      }
    } else {
      op2000Tolerance = raw.tolerance || '';
    }
  } else {
    op2000Tolerance = raw.tolerance || '';
  }

  // Feed OP2000 spec override into the numeric nominal so pipeline derives correctly
  if (user.overrides.outDrawingSpec !== null) {
    var ovSpecAsNum = parseFloat(user.overrides.outDrawingSpec);
    if (!isNaN(ovSpecAsNum)) nominal = ovSpecAsNum;
  }
  var op2000Nominal = nominal;

  // Feed OP2000 tolerance override into numeric pipeline
  if (hasOp2kTolOverride) {
    var ovTpNum = parseFloat(user.overrides.outTolPlus);
    var ovTmNum = parseFloat(user.overrides.outTolMinus);
    if (!isNaN(ovTpNum)) tolPlus = ovTpNum;
    if (!isNaN(ovTmNum)) tolMinus = ovTmNum;
    if (isNaN(ovTpNum) && !isNaN(ovTmNum)) tolPlus = ovTmNum;
    if (isNaN(ovTmNum) && !isNaN(ovTpNum)) tolMinus = ovTpNum;
  }
  var op2000InputTolerance = user.overrides.inputTolerance !== null ? user.overrides.inputTolerance : (raw.tolerance || '');

  // Store originals (pre-math) for reference
  var originalNominal = nominal;
  var originalTolPlus = tolPlus;
  var originalTolMinus = tolMinus;

  // ══════════════════════════════════════════════════════════
  // Type 4 — Auto-Nominal Centering (derives from OP2000 base)
  // ══════════════════════════════════════════════════════════
  if (user.autoNominal && (tolPlus !== tolMinus)) {
    var centered = PSB.centerNominal(nominal, tolPlus, tolMinus);
    nominal = centered.nominal;
    tolPlus = centered.tolSymmetric;
    tolMinus = centered.tolSymmetric;
  }

  // ══════════════════════════════════════════════════════════
  // Type 3 — Modifiers (derives from centered values)
  // ══════════════════════════════════════════════════════════

  // ── Plating ──────────────────────────────────────────────
  var platingAnnotation = '';
  if (user.platingMode !== 'none' && globals.platingThickness > 0) {
    var platingValue = globals.platingThickness;

    // Convert plating to same units as import if needed
    if (globals.platingUnits !== globals.importUnits) {
      platingValue = PSB.convertUnits(platingValue, globals.platingUnits, globals.importUnits);
    }

    nominal = PSB.applyPlating(nominal, platingValue, user.platingMode);

    // Build annotation string, e.g., "(+2xI)" or "(-1xE)"
    var modeMap = {
      '+1xI': '(+1xI)',
      '+2xI': '(+2xI)',
      '-1xE': '(-1xE)',
      '-2xE': '(-2xE)',
    };
    platingAnnotation = modeMap[user.platingMode] || '';
  }

  // ── Dual-unit formatting ─────────────────────────────────
  var primaryNom = nominal;
  var primaryTolPlus = tolPlus;
  var primaryTolMinus = tolMinus;

  var secondaryNom = PSB.convertUnits(nominal, importUnits, secondaryUnits);
  var secondaryTolPlus = PSB.convertUnits(tolPlus, importUnits, secondaryUnits);
  var secondaryTolMinus = PSB.convertUnits(tolMinus, importUnits, secondaryUnits);

  // ── Precision formatting ─────────────────────────────────
  var nominalStr = PSB.formatPrecision(primaryNom, primaryPrec);
  var tolStr = PSB.formatPrecision(primaryTolPlus, primaryPrec);
  var secNomStr = PSB.formatPrecision(secondaryNom, secondaryPrec);
  var secTolStr = PSB.formatPrecision(secondaryTolPlus, secondaryPrec);

  var dualNomStr = isAngle ? nominalStr + ' [Angle]' : (nominalStr + ' [' + secNomStr + ']');
  var dualTolStr;
  if (isAngle) {
    dualTolStr = tolStr;  // angles: no secondary unit
  } else if (Math.abs(primaryTolPlus - primaryTolMinus) < 1e-10) {
    dualTolStr = tolStr + ' [' + secTolStr + ']';
  } else {
    var tolMinusStr = PSB.formatPrecision(primaryTolMinus, primaryPrec);
    var secTolMinusStr = PSB.formatPrecision(secondaryTolMinus, secondaryPrec);
    dualTolStr = '+' + tolStr + ' -' + tolMinusStr + ' [+' + secTolStr + ' -' + secTolMinusStr + ']';
  }

  // ── OP2000 dual-unit display strings (UI only — Type 1+2 formatted) ──
  // Detect original decimal precision from source strings (import or override).
  // Primary display preserves original precision; secondary uses global setting.
  var op2000SpecPrecision = PSB.detectPrecision(op2000DrawingSpec);
  var op2000TolPrecision = PSB.detectPrecision(op2000Tolerance);
  var op2kSpecPrec = op2000SpecPrecision !== null ? op2000SpecPrecision : primaryPrec;
  var op2kTolPrec = op2000TolPrecision !== null ? op2000TolPrecision : primaryPrec;

  var op2kSpecNum = parseFloat(op2000DrawingSpec);
  var op2000DualSpec, op2000DualTol;
  if (!isNaN(op2kSpecNum)) {
    var op2kSpecStr = PSB.formatPrecision(op2kSpecNum, op2kSpecPrec);
    if (isAngle) {
      op2000DualSpec = op2kSpecStr + ' [Angle]';
    } else {
      var op2kSecSpec = PSB.convertUnits(op2kSpecNum, importUnits, secondaryUnits);
      var op2kSecSpecStr = PSB.formatPrecision(op2kSecSpec, secondaryPrec);
      op2000DualSpec = op2kSpecStr + ' [' + op2kSecSpecStr + ']';
    }
  } else {
    op2000DualSpec = op2000DrawingSpec;
  }
  // OP2000 dual-unit tolerance: handle symmetric vs asymmetric
  if (isAngle) {
    // Angles: show primary value only, no unit conversion
    op2000DualTol = op2000Tolerance;
  } else if (hasOp2kTolOverride && Math.abs(originalTolPlus - originalTolMinus) >= 1e-10) {
    var op2kTpStr = PSB.formatPrecision(originalTolPlus, op2kTolPrec);
    var op2kTmStr = PSB.formatPrecision(originalTolMinus, op2kTolPrec);
    var op2kSecTp = PSB.convertUnits(originalTolPlus, importUnits, secondaryUnits);
    var op2kSecTm = PSB.convertUnits(originalTolMinus, importUnits, secondaryUnits);
    var op2kSecTpStr = PSB.formatPrecision(op2kSecTp, secondaryPrec);
    var op2kSecTmStr = PSB.formatPrecision(op2kSecTm, secondaryPrec);
    op2000DualTol = '+' + op2kTpStr + ' -' + op2kTmStr + ' [+' + op2kSecTpStr + ' -' + op2kSecTmStr + ']';
  } else {
    var isAsymTol = /\+.*[-–]/.test(op2000Tolerance);
    var op2kTolNum = parseFloat(op2000Tolerance);
    if (!isAsymTol && !isNaN(op2kTolNum) && op2kTolNum !== 0) {
      var op2kTolStr = PSB.formatPrecision(op2kTolNum, op2kTolPrec);
      var op2kSecTol = PSB.convertUnits(op2kTolNum, importUnits, secondaryUnits);
      var op2kSecTolStr = PSB.formatPrecision(op2kSecTol, secondaryPrec);
      op2000DualTol = op2kTolStr + ' [' + op2kSecTolStr + ']';
    } else {
      op2000DualTol = op2000Tolerance;
    }
  }

  // ── Build output display values (other OPs) ──────────────
  // Priority: 1) Independent OUT override, 2) Derived from pipeline (OP2000 base + modifiers)
  var outDrawingSpec;
  if (user.overrides.outputSpec !== null) {
    var ovsNum = parseFloat(user.overrides.outputSpec);
    if (!isNaN(ovsNum)) {
      if (isAngle) {
        outDrawingSpec = PSB.formatPrecision(ovsNum, primaryPrec) + ' [Angle]';
      } else {
        outDrawingSpec = PSB.formatPrecision(ovsNum, primaryPrec) + ' [' +
          PSB.formatPrecision(PSB.convertUnits(ovsNum, importUnits, secondaryUnits), secondaryPrec) + ']';
      }
    } else {
      outDrawingSpec = user.overrides.outputSpec;
    }
  } else {
    outDrawingSpec = dualNomStr;
  }

  // OUT tolerance: independent override or derived from pipeline
  var hasOutTolOverride = user.overrides.outputTolPlus !== null || user.overrides.outputTolMinus !== null;
  var finalTolPlus = primaryTolPlus;
  var finalTolMinus = primaryTolMinus;
  var outTolerance;

  if (hasOutTolOverride) {
    var outOvPlus = parseFloat(user.overrides.outputTolPlus);
    var outOvMinus = parseFloat(user.overrides.outputTolMinus);
    if (isNaN(outOvPlus) && !isNaN(outOvMinus)) outOvPlus = outOvMinus;
    if (isNaN(outOvMinus) && !isNaN(outOvPlus)) outOvMinus = outOvPlus;
    if (!isNaN(outOvPlus) && !isNaN(outOvMinus)) {
      finalTolPlus = outOvPlus;
      finalTolMinus = outOvMinus;
      if (Math.abs(outOvPlus - outOvMinus) < 1e-10) {
        outTolerance = PSB.formatPrecision(outOvPlus, primaryPrec) + ' [' +
          PSB.formatPrecision(PSB.convertUnits(outOvPlus, importUnits, secondaryUnits), secondaryPrec) + ']';
      } else {
        var ftp = PSB.formatPrecision(outOvPlus, primaryPrec);
        var ftm = PSB.formatPrecision(outOvMinus, primaryPrec);
        var sftp = PSB.formatPrecision(PSB.convertUnits(outOvPlus, importUnits, secondaryUnits), secondaryPrec);
        var sftm = PSB.formatPrecision(PSB.convertUnits(outOvMinus, importUnits, secondaryUnits), secondaryPrec);
        outTolerance = '+' + ftp + ' -' + ftm + ' [+' + sftp + ' -' + sftm + ']';
      }
    } else {
      outTolerance = dualTolStr;
    }
  } else {
    outTolerance = dualTolStr;
  }

  // ── Pin/Gage computation ─────────────────────────────────
  // Uses final OUT tolerance values (which may be independently overridden)
  var pinGageStr = '';
  var pinGageAutoStr = '';
  if (user.pinGageEnabled) {
    var pgIsAsym = Math.abs(finalTolPlus - finalTolMinus) >= 1e-10;
    if (user.inspectionEquipment === 'Gage Block' || pgIsAsym) {
      var gb = PSB.computeGageBlock(primaryNom, finalTolPlus, finalTolMinus, primaryPrec);
      pinGageAutoStr = gb.formatted;
    } else {
      var pg = PSB.computePinGage(primaryNom, finalTolPlus, primaryPrec);
      pinGageAutoStr = pg.formatted;
    }
    pinGageStr = user.overrides.pinGageValue !== null ? user.overrides.pinGageValue : pinGageAutoStr;
  }

  var outNominal = dualNomStr;
  if (platingAnnotation) {
    // Insert annotation before bracket notation so formatDualDisplay() colors correctly
    // e.g. "33.000 (+2xI) [1.2992]" instead of "33.000 [1.2992] (+2xI)"
    outNominal = nominalStr + ' ' + platingAnnotation + ' [' + secNomStr + ']';
  }

  // ── Output Tag (overrideable per Rule 6) ─────────────────
  var outputTag;
  if (user.overrides.outputTag !== null && !isAutoGeneratedTag(user.overrides.outputTag)) {
    // Truly custom tag — preserve it
    outputTag = user.overrides.outputTag;
  } else {
    outputTag = generateOutputTag(
      effDimTag,
      user.inspectionFrequency || '',
      false  // non-OP2000 for display
    );
  }

  // ── Assemble computed object ─────────────────────────────
  row.computed = {
    isNote: false,
    isAngle: isAngle,
    dimTag: effDimTag,
    outputTag: outputTag,
    specUnit1: op2000SpecUnit1,
    specUnit2: op2000SpecUnit2,
    specUnit3: op2000SpecUnit3,
    inputSpec: raw.drawingSpec || '',
    inputTolerance: op2000InputTolerance,

    // OP2000 base values (Type 1 + Type 2 only)
    op2000DrawingSpec: op2000DrawingSpec,
    op2000Nominal: op2000Nominal,
    op2000Tolerance: op2000Tolerance,
    op2000DualSpec: op2000DualSpec,
    op2000DualTol: op2000DualTol,
    op2000SpecPrecision: op2000SpecPrecision,  // original decimal places (null if non-numeric)
    op2000TolPrecision: op2000TolPrecision,

    // Other OP values (derived from OP2000 base + Types 3 & 4)
    outDrawingSpec: outDrawingSpec,
    outNominal: user.overrides.outNominal !== null ? user.overrides.outNominal : outNominal,
    outTolerance: outTolerance,
    pinGage: pinGageStr,
    pinGageAuto: pinGageAutoStr,
    platingAnnotation: platingAnnotation,
    platingMode: user.platingMode,

    // OP2000 numeric tol values (for edit UI population)
    op2kTolPlus: originalTolPlus,
    op2kTolMinus: originalTolMinus,
    // Final OUT tolerance numeric values (pipeline or independent override)
    outTolPlus: finalTolPlus,
    outTolMinus: finalTolMinus,

    original: {
      nominal: originalNominal,
      tolPlus: originalTolPlus,
      tolMinus: originalTolMinus,
    },
    output: {
      nominal: primaryNom,
      tolPlus: primaryTolPlus,
      tolMinus: primaryTolMinus,
    },
    secondary: {
      nominal: secondaryNom,
      tolPlus: secondaryTolPlus,
      tolMinus: secondaryTolMinus,
    },
    // Export-ready values (converted to exportUnits, no brackets)
    exportNominal: (function() {
      var eu = globals.exportUnits || 'inch';
      var ePrec = eu === 'inch' ? globals.inchPrecision : globals.mmPrecision;
      var eNom = PSB.convertUnits(primaryNom, importUnits, eu);
      return PSB.formatPrecision(eNom, ePrec);
    })(),
    exportTolerance: (function() {
      var eu = globals.exportUnits || 'inch';
      var ePrec = eu === 'inch' ? globals.inchPrecision : globals.mmPrecision;
      var eTolPlus = PSB.convertUnits(finalTolPlus, importUnits, eu);
      var eTolMinus = PSB.convertUnits(finalTolMinus, importUnits, eu);
      if (Math.abs(eTolPlus - eTolMinus) < 1e-10) {
        return PSB.formatPrecision(eTolPlus, ePrec);
      }
      return '+' + PSB.formatPrecision(eTolPlus, ePrec) + ' -' + PSB.formatPrecision(eTolMinus, ePrec);
    })(),

    status: user.status,
    ipc: user.ipc,
    inspectionEquipment: user.inspectionEquipment,
    inspectionFrequency: user.inspectionFrequency,
    includeOps: Object.assign({}, user.includeOps),
  };

  return row;
}

/**
 * Get flat export data for a row + specific op.
 * OP2000 returns Type 1+2 values (parsed + overridden).
 * Other OPs return full pipeline values (Types 1-4).
 *
 * @param {Object} row
 * @param {number} opNumber
 * @param {Object} globals
 * @returns {Object} flat object matching CSV columns
 */
function getExportData(row, opNumber, globals) {
  var raw = row.raw;
  var user = row.user;
  var computed = row.computed;
  var isOp2000 = opNumber === 2000;

  // Output Tag: OP2000 always uses raw padded dim tag; other OPs use computed (which respects overrides)
  var outputTag = isOp2000
    ? generateOutputTag(computed.dimTag || '', computed.inspectionFrequency || '', true)
    : (computed.outputTag || generateOutputTag(computed.dimTag || '', computed.inspectionFrequency || '', false));

  if (computed.isNote) {
    // Notes export with drawing spec text and any user overrides
    return {
      'Internal Part #': '',
      'Op #': opNumber,
      'Dim Tag #': outputTag,
      'Ref Loc': raw.refLoc || '',
      'Char Dsg': '',
      'Spec Unit 1': computed.specUnit1,
      'Drawing Spec': computed.outDrawingSpec,
      'Spec Unit 2': computed.specUnit2,
      'Spec Unit 3': computed.specUnit3,
      'Inspec Equip': computed.inspectionEquipment || '',
      'Nom Dim': computed.outNominal,
      'Tol ±': computed.outTolerance,
      'IPC?': computed.ipc ? 'TRUE' : '',
      'Inspection Frequency': computed.inspectionFrequency || '',
      'Show Dim When?': '',
    };
  }

  if (isOp2000) {
    // OP2000: Type 1 (parsing) + Type 2 (overrides) only. No math, no unit conversion.
    return {
      'Internal Part #': '',
      'Op #': 2000,
      'Dim Tag #': outputTag,
      'Ref Loc': raw.refLoc || '',
      'Char Dsg': raw.charDsg || '',
      'Spec Unit 1': computed.specUnit1,
      'Drawing Spec': computed.op2000DrawingSpec,
      'Spec Unit 2': computed.specUnit2,
      'Spec Unit 3': computed.specUnit3,
      'Inspec Equip': computed.inspectionEquipment || '',
      'Nom Dim': computed.op2000DrawingSpec,
      'Tol ±': computed.op2000Tolerance,
      'IPC?': computed.ipc ? 'TRUE' : '',
      'Inspection Frequency': computed.inspectionFrequency || '',
      'Show Dim When?': '',
    };
  }

  // Non-OP2000: export uses secondary (converted) unit values, no brackets
  var exportNom = computed.exportNominal || '';
  if (computed.platingAnnotation) {
    exportNom = exportNom + ' ' + computed.platingAnnotation;
  }
  if (computed.pinGage) {
    exportNom = computed.pinGage;
  }
  return {
    'Internal Part #': '',
    'Op #': opNumber,
    'Dim Tag #': outputTag,
    'Ref Loc': raw.refLoc || '',
    'Char Dsg': '',
    'Spec Unit 1': computed.specUnit1,
    'Drawing Spec': computed.exportNominal || '',
    'Spec Unit 2': computed.specUnit2,
    'Spec Unit 3': computed.specUnit3,
    'Inspec Equip': computed.inspectionEquipment || '',
    'Nom Dim': exportNom,
    'Tol ±': computed.exportTolerance || '',
    'IPC?': computed.ipc ? 'TRUE' : '',
    'Inspection Frequency': computed.inspectionFrequency || '',
    'Show Dim When?': '',
  };
}

/**
 * Default FAI state for a row — null means no measurements yet.
 * @returns {null}
 */
function defaultFaiState() { return null; }

/**
 * Reset row ID counter (useful for testing)
 */
function resetIdCounter() {
  _nextId = 1;
}

// ── Export to namespace ───────────────────────────────────
PSB.defaultGlobals = defaultGlobals;
PSB.defaultUserState = defaultUserState;
PSB.defaultFaiState = defaultFaiState;
PSB.createRow = createRow;
PSB.createBalloonRow = createBalloonRow;
PSB.effectiveDimTag = effectiveDimTag;
PSB.recompute = recompute;
PSB.getExportData = getExportData;
PSB.resetIdCounter = resetIdCounter;
PSB.generateOutputTag = generateOutputTag;
