/**
 * dataModel.js — Single Source of Truth
 *
 * Every row: { id, raw, user, computed }
 * - raw: immutable parsed import data
 * - user: user overrides and settings
 * - computed: derived output (what UI/export reads)
 *
 * Rule: table, sidebar, and export ALL read from `computed`.
 * Call recompute() whenever raw, user, or globals change.
 */

window.PSB = window.PSB || {};

// ── Row ID counter ────────────────────────────────────────
var _nextId = 1;

// ── Frequency → Letter mapping (fixed, never dynamic) ────
var FREQ_LETTER_MAP = {
  '1 in 1': 'A',
  '1 in 2': 'B',
  '1 in 3': 'C',
  '1 in 4': 'D',
  '1 in 5': 'E',
  '1 in 10': 'F',
  '1 in 20': 'G',
  '1 in 50': 'H',
  'First and Last': 'I',
};

/**
 * Generate the Output Tag for a dim tag + frequency.
 *
 * Non-OP2000: <LetterPrefix>REF-<zero-padded dim tag>
 * OP2000: raw dim tag only (no REF-, no letter)
 *
 * @param {string} dimTag — raw dim tag value
 * @param {string} frequency — inspection frequency string
 * @param {boolean} isOp2000
 * @returns {string}
 */
function generateOutputTag(dimTag, frequency, isOp2000) {
  // Zero-pad to 2 digits if numeric
  var padded = /^\d+$/.test(dimTag) ? dimTag.padStart(2, '0') : dimTag;

  if (isOp2000) {
    return padded;
  }

  var letter = FREQ_LETTER_MAP[frequency] || '';
  return letter + 'REF-' + padded;
}

/**
 * Check if an output tag matches an auto-generated pattern.
 * Auto-generated: "REF-07", "AREF-07", "BREF-13", "07" (OP2000 padded)
 * If it matches, frequency changes can safely regenerate it.
 */
function isAutoGeneratedTag(tag) {
  if (!tag) return true;
  return /^[A-I]?REF-\d+$/.test(tag) || /^\d{1,2}$/.test(tag);
}

/**
 * Default global settings
 */
function defaultGlobals() {
  return {
    importUnits: 'mm',        // 'mm' or 'inch'
    displayUnits: 'inch',     // 'mm', 'inch', or 'both'
    exportUnits: 'inch',
    platingThickness: 0,
    platingUnits: 'inch',
    inchPrecision: 4,
    mmPrecision: 3,
    ops: [50, 60],            // default OPs
    equipmentList: [
      'Calipers',
      'Micrometer',
      'Optical C.',
      'CMM',
      'Height Gage',
      'Gage Block',
      'GO / NO-GO',
      'PASS/FAIL',
      'Drop Indicator',
      'N/A',
    ],
  };
}

/**
 * Default user overrides for a single row
 */
function defaultUserState() {
  return {
    includeOps: {},          // { [opNumber]: true/false }
    ipc: false,
    isNote: false,
    autoNominal: true,
    platingMode: 'none',     // 'none', '+1xI', '+2xI', '-1xE', '-2xE'
    inspectionFrequency: '',
    inspectionEquipment: '',
    pinGageEnabled: false,
    status: 'none',          // 'none', 'edited', 'complete'
    overrides: {
      outDrawingSpec: null,  // null = use computed, string = manual override
      outTolerance: null,
      pinGageValue: null,
      specUnit1: null,
      specUnit2: null,
      specUnit3: null,
      outNominal: null,
      inputTolerance: null,
      outputTag: null,       // null = auto-generate, string = manual override
    },
  };
}

/**
 * Create a new row from raw CSV data
 * @param {Object} rawData — parsed CSV fields
 * @returns {Object} row — { id, raw, user, computed }
 */
function createRow(rawData) {
  var row = {
    id: _nextId++,
    raw: Object.freeze(Object.assign({}, rawData)),
    user: defaultUserState(),
    computed: {},
  };

  // Auto-detect notes from drawingSpec
  var featureType = PSB.detectFeatureType(rawData.drawingSpec || '');
  if (featureType === 'note' || featureType === 'gdt' || featureType === 'thread') {
    row.user.isNote = true;
  }

  // Also detect GD&T from specUnit2 (e.g., Concentricity, Position, Flatness)
  if (!row.user.isNote && rawData.specUnit2) {
    var su2 = rawData.specUnit2.trim().toLowerCase();
    var gdtSu2 = ['concentricity', 'position', 'flatness', 'perpendicular',
      'parallel', 'surf profile', 'angular', 'total runout', 'runout'];
    for (var i = 0; i < gdtSu2.length; i++) {
      if (su2.indexOf(gdtSu2[i]) >= 0) {
        row.user.isNote = true;
        break;
      }
    }
  }

  return row;
}

/**
 * Recompute a row's `computed` object from raw + user + globals.
 * This is the ONLY place calculations happen.
 *
 * @param {Object} row — the row to recompute
 * @param {Object} globals — global settings
 * @returns {Object} row — same row, mutated with new computed values
 */
function recompute(row, globals) {
  var raw = row.raw;
  var user = row.user;

  // ── Step 0: If note, skip all math ─────────────────────
  if (user.isNote) {
    var ov = user.overrides || {};
    var noteOutputTag = (ov.outputTag !== null && !isAutoGeneratedTag(ov.outputTag))
      ? ov.outputTag
      : generateOutputTag(raw.dimTag || '', user.inspectionFrequency || '', false);
    row.computed = {
      isNote: true,
      dimTag: raw.dimTag || '',
      outputTag: noteOutputTag,
      drawingSpec: raw.drawingSpec || '',
      outDrawingSpec: ov.outDrawingSpec !== null ? ov.outDrawingSpec : (raw.drawingSpec || ''),
      inputSpec: raw.drawingSpec || '',
      specUnit1: ov.specUnit1 !== null ? ov.specUnit1 : (raw.specUnit1 || ''),
      specUnit2: ov.specUnit2 !== null ? ov.specUnit2 : (raw.specUnit2 || ''),
      specUnit3: ov.specUnit3 !== null ? ov.specUnit3 : (raw.specUnit3 || ''),
      // OP2000 fields (consistent shape with non-note rows — preserve raw values)
      op2000DrawingSpec: ov.outDrawingSpec !== null ? ov.outDrawingSpec : (raw.drawingSpec || ''),
      op2000Nominal: 0,
      op2000Tolerance: ov.outTolerance !== null ? ov.outTolerance : (raw.tolerance || ''),
      op2000DualSpec: ov.outDrawingSpec !== null ? ov.outDrawingSpec : (raw.drawingSpec || ''),
      op2000DualTol: ov.outTolerance !== null ? ov.outTolerance : (raw.tolerance || ''),
      outNominal: ov.outNominal !== null ? ov.outNominal : (raw.nominal || ''),
      outTolerance: ov.outTolerance !== null ? ov.outTolerance : (raw.tolerance || ''),
      inputTolerance: ov.inputTolerance !== null ? ov.inputTolerance : (raw.tolerance || ''),
      pinGage: ov.pinGageValue !== null ? ov.pinGageValue : '',
      platingAnnotation: '',
      platingMode: 'none',
      status: user.status,
      ipc: user.ipc,
      inspectionEquipment: user.inspectionEquipment,
      inspectionFrequency: user.inspectionFrequency,
      includeOps: Object.assign({}, user.includeOps),
      original: { nominal: 0, tolPlus: 0, tolMinus: 0 },
      output: { nominal: 0, tolPlus: 0, tolMinus: 0 },
    };
    return row;
  }

  // ══════════════════════════════════════════════════════════
  // Type 1 — Parsing: clean up raw data into correct columns
  // ══════════════════════════════════════════════════════════
  var specUnits = PSB.parseSpecUnits(raw.drawingSpec || '');
  var tolParsed = PSB.parseTolerance(raw.toleranceText || raw.tolerance || '');

  var nominal = parseFloat(raw.nominalText || raw.nominal || raw.drawingSpec) || 0;
  var tolPlus = tolParsed.tolPlus;
  var tolMinus = tolParsed.tolMinus;

  // If tolerance was a single ± value from CSV
  if (tolPlus === 0 && tolMinus === 0 && raw.tolerance) {
    var t = parseFloat(raw.tolerance);
    if (!isNaN(t)) {
      tolPlus = t;
      tolMinus = t;
    }
  }

  // ══════════════════════════════════════════════════════════
  // Type 2 — Manual Overrides: apply user corrections
  // After this point we have the OP2000 base values.
  // ══════════════════════════════════════════════════════════
  var op2000SpecUnit1 = user.overrides.specUnit1 !== null ? user.overrides.specUnit1 : (raw.specUnit1 || specUnits.su1 || '');
  var op2000SpecUnit2 = user.overrides.specUnit2 !== null ? user.overrides.specUnit2 : (raw.specUnit2 || specUnits.su2 || '');
  var op2000SpecUnit3 = user.overrides.specUnit3 !== null ? user.overrides.specUnit3 : (raw.specUnit3 || specUnits.su3 || '');
  var op2000DrawingSpec = user.overrides.outDrawingSpec !== null ? user.overrides.outDrawingSpec : (raw.drawingSpec || '');
  var op2000Nominal = nominal;  // numeric, from parsed raw
  var op2000Tolerance = user.overrides.outTolerance !== null ? user.overrides.outTolerance : (raw.tolerance || '');
  var op2000InputTolerance = user.overrides.inputTolerance !== null ? user.overrides.inputTolerance : (raw.tolerance || '');

  // Store originals (pre-math) for reference
  var originalNominal = nominal;
  var originalTolPlus = tolPlus;
  var originalTolMinus = tolMinus;

  // ══════════════════════════════════════════════════════════
  // Type 4 — Auto-Nominal Centering (derives from OP2000 base)
  // ══════════════════════════════════════════════════════════
  if (user.autoNominal && !tolParsed.isSymmetric && (tolPlus !== tolMinus)) {
    var centered = PSB.centerNominal(nominal, tolPlus, tolMinus);
    nominal = centered.nominal;
    tolPlus = centered.tolSymmetric;
    tolMinus = centered.tolSymmetric;
  }

  // ══════════════════════════════════════════════════════════
  // Type 3 — Modifiers (derives from centered values)
  // ══════════════════════════════════════════════════════════

  // ── Plating ──────────────────────────────────────────────
  var platingAnnotation = '';
  if (user.platingMode !== 'none' && globals.platingThickness > 0) {
    var platingValue = globals.platingThickness;

    // Convert plating to same units as import if needed
    if (globals.platingUnits !== globals.importUnits) {
      platingValue = PSB.convertUnits(platingValue, globals.platingUnits, globals.importUnits);
    }

    nominal = PSB.applyPlating(nominal, platingValue, user.platingMode);

    // Build annotation string, e.g., "(+2xI)" or "(-1xE)"
    var modeMap = {
      '+1xI': '(+1xI)',
      '+2xI': '(+2xI)',
      '-1xE': '(-1xE)',
      '-2xE': '(-2xE)',
    };
    platingAnnotation = modeMap[user.platingMode] || '';
  }

  // ── Dual-unit formatting ─────────────────────────────────
  var importUnits = globals.importUnits || 'mm';
  var secondaryUnits = importUnits === 'mm' ? 'inch' : 'mm';
  var primaryPrec = importUnits === 'inch' ? globals.inchPrecision : globals.mmPrecision;
  var secondaryPrec = secondaryUnits === 'inch' ? globals.inchPrecision : globals.mmPrecision;

  var primaryNom = nominal;
  var primaryTolPlus = tolPlus;
  var primaryTolMinus = tolMinus;

  var secondaryNom = PSB.convertUnits(nominal, importUnits, secondaryUnits);
  var secondaryTolPlus = PSB.convertUnits(tolPlus, importUnits, secondaryUnits);
  var secondaryTolMinus = PSB.convertUnits(tolMinus, importUnits, secondaryUnits);

  // ── Precision formatting ─────────────────────────────────
  var nominalStr = PSB.formatPrecision(primaryNom, primaryPrec);
  var tolStr = PSB.formatPrecision(primaryTolPlus, primaryPrec);
  var secNomStr = PSB.formatPrecision(secondaryNom, secondaryPrec);
  var secTolStr = PSB.formatPrecision(secondaryTolPlus, secondaryPrec);

  var dualNomStr = nominalStr + ' [' + secNomStr + ']';
  var dualTolStr = tolStr + ' [' + secTolStr + ']';

  // ── OP2000 dual-unit display strings (UI only — Type 1+2 formatted) ──
  // Detect original decimal precision from source strings (import or override).
  // Primary display preserves original precision; secondary uses global setting.
  var op2000SpecPrecision = PSB.detectPrecision(op2000DrawingSpec);
  var op2000TolPrecision = PSB.detectPrecision(op2000Tolerance);
  var op2kSpecPrec = op2000SpecPrecision !== null ? op2000SpecPrecision : primaryPrec;
  var op2kTolPrec = op2000TolPrecision !== null ? op2000TolPrecision : primaryPrec;

  var op2kSpecNum = parseFloat(op2000DrawingSpec);
  var op2000DualSpec, op2000DualTol;
  if (!isNaN(op2kSpecNum)) {
    var op2kSpecStr = PSB.formatPrecision(op2kSpecNum, op2kSpecPrec);
    var op2kSecSpec = PSB.convertUnits(op2kSpecNum, importUnits, secondaryUnits);
    var op2kSecSpecStr = PSB.formatPrecision(op2kSecSpec, secondaryPrec);
    op2000DualSpec = op2kSpecStr + ' [' + op2kSecSpecStr + ']';
  } else {
    op2000DualSpec = op2000DrawingSpec;
  }
  // Preserve asymmetric tolerance notation (e.g., +0.001-0) — don't dual-format
  var isAsymTol = /\+.*[-–]/.test(op2000Tolerance);
  var op2kTolNum = parseFloat(op2000Tolerance);
  if (!isAsymTol && !isNaN(op2kTolNum) && op2kTolNum !== 0) {
    var op2kTolStr = PSB.formatPrecision(op2kTolNum, op2kTolPrec);
    var op2kSecTol = PSB.convertUnits(op2kTolNum, importUnits, secondaryUnits);
    var op2kSecTolStr = PSB.formatPrecision(op2kSecTol, secondaryPrec);
    op2000DualTol = op2kTolStr + ' [' + op2kSecTolStr + ']';
  } else {
    op2000DualTol = op2000Tolerance;
  }

  // ── Pin/Gage computation ─────────────────────────────────
  var pinGageStr = '';
  if (user.pinGageEnabled && user.overrides.pinGageValue !== null) {
    pinGageStr = user.overrides.pinGageValue;
  } else if (user.pinGageEnabled) {
    var pg = PSB.computePinGage(secondaryNom, secondaryTolPlus, secondaryPrec);
    pinGageStr = pg.formatted;
  }

  // ── Build output display values (other OPs) ──────────────
  var outDrawingSpec;
  if (user.overrides.outDrawingSpec !== null) {
    var ovSpecNum = parseFloat(user.overrides.outDrawingSpec);
    if (!isNaN(ovSpecNum)) {
      var ovSpecStr = PSB.formatPrecision(ovSpecNum, primaryPrec);
      var ovSecSpec = PSB.convertUnits(ovSpecNum, importUnits, secondaryUnits);
      var ovSecSpecStr = PSB.formatPrecision(ovSecSpec, secondaryPrec);
      outDrawingSpec = ovSpecStr + ' [' + ovSecSpecStr + ']';
    } else {
      outDrawingSpec = user.overrides.outDrawingSpec;
    }
  } else {
    outDrawingSpec = dualNomStr;
  }

  var outTolerance;
  if (user.overrides.outTolerance !== null) {
    var ovTolNum = parseFloat(user.overrides.outTolerance);
    var isAsymOvTol = /\+.*[-–]/.test(user.overrides.outTolerance);
    if (!isAsymOvTol && !isNaN(ovTolNum) && ovTolNum !== 0) {
      var ovTolStr = PSB.formatPrecision(ovTolNum, primaryPrec);
      var ovSecTol = PSB.convertUnits(ovTolNum, importUnits, secondaryUnits);
      var ovSecTolStr = PSB.formatPrecision(ovSecTol, secondaryPrec);
      outTolerance = ovTolStr + ' [' + ovSecTolStr + ']';
    } else {
      outTolerance = user.overrides.outTolerance;
    }
  } else {
    outTolerance = dualTolStr;
  }

  var outNominal = dualNomStr;
  if (platingAnnotation) {
    outNominal = dualNomStr + ' ' + platingAnnotation;
  }

  // ── Output Tag (overrideable per Rule 6) ─────────────────
  var outputTag;
  if (user.overrides.outputTag !== null && !isAutoGeneratedTag(user.overrides.outputTag)) {
    // Truly custom tag — preserve it
    outputTag = user.overrides.outputTag;
  } else {
    outputTag = generateOutputTag(
      raw.dimTag || '',
      user.inspectionFrequency || '',
      false  // non-OP2000 for display
    );
  }

  // ── Assemble computed object ─────────────────────────────
  row.computed = {
    isNote: false,
    dimTag: raw.dimTag || '',
    outputTag: outputTag,
    specUnit1: op2000SpecUnit1,
    specUnit2: op2000SpecUnit2,
    specUnit3: op2000SpecUnit3,
    inputSpec: raw.drawingSpec || '',
    inputTolerance: op2000InputTolerance,

    // OP2000 base values (Type 1 + Type 2 only)
    op2000DrawingSpec: op2000DrawingSpec,
    op2000Nominal: op2000Nominal,
    op2000Tolerance: op2000Tolerance,
    op2000DualSpec: op2000DualSpec,
    op2000DualTol: op2000DualTol,
    op2000SpecPrecision: op2000SpecPrecision,  // original decimal places (null if non-numeric)
    op2000TolPrecision: op2000TolPrecision,

    // Other OP values (derived from OP2000 base + Types 3 & 4)
    outDrawingSpec: outDrawingSpec,
    outNominal: user.overrides.outNominal !== null ? user.overrides.outNominal : outNominal,
    outTolerance: outTolerance,
    pinGage: pinGageStr,
    platingAnnotation: platingAnnotation,
    platingMode: user.platingMode,

    original: {
      nominal: originalNominal,
      tolPlus: originalTolPlus,
      tolMinus: originalTolMinus,
    },
    output: {
      nominal: primaryNom,
      tolPlus: primaryTolPlus,
      tolMinus: primaryTolMinus,
    },
    secondary: {
      nominal: secondaryNom,
      tolPlus: secondaryTolPlus,
      tolMinus: secondaryTolMinus,
    },
    // Export-ready values (converted to exportUnits, no brackets)
    exportNominal: (function() {
      var eu = globals.exportUnits || 'inch';
      var ePrec = eu === 'inch' ? globals.inchPrecision : globals.mmPrecision;
      var eNom = PSB.convertUnits(primaryNom, importUnits, eu);
      return PSB.formatPrecision(eNom, ePrec);
    })(),
    exportTolerance: (function() {
      var eu = globals.exportUnits || 'inch';
      var ePrec = eu === 'inch' ? globals.inchPrecision : globals.mmPrecision;
      var eTol = PSB.convertUnits(primaryTolPlus, importUnits, eu);
      return PSB.formatPrecision(eTol, ePrec);
    })(),

    status: user.status,
    ipc: user.ipc,
    inspectionEquipment: user.inspectionEquipment,
    inspectionFrequency: user.inspectionFrequency,
    includeOps: Object.assign({}, user.includeOps),
  };

  return row;
}

/**
 * Get flat export data for a row + specific op.
 * OP2000 returns Type 1+2 values (parsed + overridden).
 * Other OPs return full pipeline values (Types 1-4).
 *
 * @param {Object} row
 * @param {number} opNumber
 * @param {Object} globals
 * @returns {Object} flat object matching CSV columns
 */
function getExportData(row, opNumber, globals) {
  var raw = row.raw;
  var user = row.user;
  var computed = row.computed;
  var isOp2000 = opNumber === 2000;

  // Output Tag: OP2000 always uses raw padded dim tag; other OPs use computed (which respects overrides)
  var outputTag = isOp2000
    ? generateOutputTag(computed.dimTag || '', computed.inspectionFrequency || '', true)
    : (computed.outputTag || generateOutputTag(computed.dimTag || '', computed.inspectionFrequency || '', false));

  if (computed.isNote) {
    // Notes export with drawing spec text and any user overrides
    return {
      'Internal Part #': '',
      'Op #': opNumber,
      'Dim Tag #': outputTag,
      'Ref Loc': raw.refLoc || '',
      'Char Dsg': '',
      'Spec Unit 1': computed.specUnit1,
      'Drawing Spec': computed.outDrawingSpec,
      'Spec Unit 2': computed.specUnit2,
      'Spec Unit 3': computed.specUnit3,
      'Inspec Equip': computed.inspectionEquipment || '',
      'Nom Dim': computed.outNominal,
      'Tol ±': computed.outTolerance,
      'IPC?': computed.ipc ? 'TRUE' : '',
      'Inspection Frequency': computed.inspectionFrequency || '',
      'Show Dim When?': '',
    };
  }

  if (isOp2000) {
    // OP2000: Type 1 (parsing) + Type 2 (overrides) only. No math, no unit conversion.
    return {
      'Internal Part #': '',
      'Op #': 2000,
      'Dim Tag #': outputTag,
      'Ref Loc': raw.refLoc || '',
      'Char Dsg': raw.charDsg || '',
      'Spec Unit 1': computed.specUnit1,
      'Drawing Spec': computed.op2000DrawingSpec,
      'Spec Unit 2': computed.specUnit2,
      'Spec Unit 3': computed.specUnit3,
      'Inspec Equip': computed.inspectionEquipment || '',
      'Nom Dim': computed.op2000DrawingSpec,
      'Tol ±': computed.op2000Tolerance,
      'IPC?': computed.ipc ? 'TRUE' : '',
      'Inspection Frequency': computed.inspectionFrequency || '',
      'Show Dim When?': '',
    };
  }

  // Non-OP2000: export uses secondary (converted) unit values, no brackets
  var exportNom = computed.exportNominal || '';
  if (computed.platingAnnotation) {
    exportNom = exportNom + ' ' + computed.platingAnnotation;
  }
  return {
    'Internal Part #': '',
    'Op #': opNumber,
    'Dim Tag #': outputTag,
    'Ref Loc': raw.refLoc || '',
    'Char Dsg': '',
    'Spec Unit 1': computed.specUnit1,
    'Drawing Spec': computed.exportNominal || '',
    'Spec Unit 2': computed.specUnit2,
    'Spec Unit 3': computed.specUnit3,
    'Inspec Equip': computed.inspectionEquipment || '',
    'Nom Dim': exportNom,
    'Tol ±': computed.exportTolerance || '',
    'IPC?': computed.ipc ? 'TRUE' : '',
    'Inspection Frequency': computed.inspectionFrequency || '',
    'Show Dim When?': '',
  };
}

/**
 * Reset row ID counter (useful for testing)
 */
function resetIdCounter() {
  _nextId = 1;
}

// ── Export to namespace ───────────────────────────────────
PSB.defaultGlobals = defaultGlobals;
PSB.defaultUserState = defaultUserState;
PSB.createRow = createRow;
PSB.recompute = recompute;
PSB.getExportData = getExportData;
PSB.resetIdCounter = resetIdCounter;
PSB.generateOutputTag = generateOutputTag;
